---
docker_edition: 'ce'
docker_package: "docker-{{ docker_edition }}"
docker_package_state: present

docker_install_compose: true
docker_compose_version: "1.29.2"
docker_compose_arch: x86_64
docker_compose_path: /usr/local/bin/docker-compose

docker_users:
  - "{{ ansible_user }}"
